#!/bin/bash

# First we see if we can build correctly

echo "Compiling..."
tsc --declarations pressgangccms.ts
if [ $? -eq 0 ]; 
then 
	# setup environment for the tests
	source environment

	echo "Running tests..."
	# Now we see if we can pass the tests
	jasmine-node --verbose ./../tests/wet-tests.spec.js;

	if [ $? -eq 0 ]; then
		echo "Deploying..."
		cp pressgangccms.d.ts ./../
		cp pressgangccms.js ./../;

	fi
fi

